### ISSUE TITLE
App crushed on local notification

### ISSUE THREAD

**Issue by rozx** [ryanw3bb/unity-native-toolkit#1]
```
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/NotificationCompat$Builder;
        at com.secondfury.nativetoolkit.LocalNotification.onReceive(LocalNotification.java:42)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3379)
        at android.app.ActivityThread.access$1200(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.NotificationCompat$Builder" on path: DexPathList[[zip file "/data/app/com.hitgrab.playground-LZSzirZBxb9mYyIHOhkm9Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.hitgrab.playground-LZSzirZBxb9mYyIHOhkm9Q==/lib/x86, /data/app/com.hitgrab.playground-LZSzirZBxb9mYyIHOhkm9Q==/base.apk!/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.secondfury.nativetoolkit.LocalNotification.onReceive(LocalNotification.java:42) 
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3379) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

On Android virtual machine, android version API 28, all permissions granted.

**Comment by ryanw3bb** [comment]
Fixed as of the latest commit, there was a missing lib (support-compat)
