### ISSUE TITLE
Camera Shot crashes app

### ISSUE THREAD

**Issue by EricBatlle** [ryanw3bb/unity-native-toolkit#33]
Seems the result of a nullpointer exception derived of the non-existance of directory.

```
2020-08-18 20:45:23.576 21941-21941/com.DefaultCompany.Unity D/Native Toolkit: Failed to create directory
2020-08-18 20:45:23.576 21941-21941/com.DefaultCompany.Unity D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2020-08-18 20:45:23.577 21941-21941/com.DefaultCompany.Unity E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.DefaultCompany.Unity, PID: 21941
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.DefaultCompany.Unity/com.secondfury.nativetoolkit.MainActivity}: java.lang.NullPointerException: file
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.NullPointerException: file
        at android.net.Uri.fromFile(Uri.java:467)
        at com.secondfury.nativetoolkit.MainActivity.getOutputMediaFileUri(MainActivity.java:183)
        at com.secondfury.nativetoolkit.MainActivity.onCreate(MainActivity.java:67)
        at android.app.Activity.performCreate(Activity.java:7224)
        at android.app.Activity.performCreate(Activity.java:7213)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6806) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
2020-08-18 20:45:23.585 2698-2758/? I/octvm_klo: klo lock
2020-08-18 20:45:23.585 1704-3026/? W/ActivityManager:   Force finishing activity com.DefaultCompany.Unity/com.secondfury.nativetoolkit.MainActivity
2020-08-18 20:45:23.586 1704-3026/? D/ActivityTrigger: ActivityTrigger activityPauseTrigger 
2020-08-18 20:45:23.588 1704-3026/? W/ActivityManager:   Force finishing activity com.DefaultCompany.Unity/com.unity3d.player.UnityPlayerActivity
2020-08-18 20:45:23.590 2209-6784/? D/Launcher: get showing item successandroid.graphics.Bitmap@e5f6acb
2020-08-18 20:45:23.592 1704-1878/? D/libEGL: eglInitialize: enter
2020-08-18 20:45:23.592 1704-1878/? D/libEGL: eglInitialize: exit(res=1)
2020-08-18 20:45:23.592 1704-1878/? I/OpenGLRenderer: Initialized EGL, version 1.4
```

**Comment by SuckerPunch1978** [comment]
Hi, I need to shot down the cameras in this big room probably by brutforcing Wi-Fi because csmeras are connected to it. Sny suggestion?
